spring.application.name=RateLimiterTestApp

server.port=8081
rate-limiter.policies.test=5c2bdc90-5ac6-4bb7-b68d-8f845c88df0e
rate-limiter.url=http://localhost:8080
rate-limiter.apikey=961dec4f-058c-4a4c-be48-01ab84f344e4